language: ruby
cache: bundler
sudo: false
rvm: 2.3.3

install: script/bootstrap
script: script/cibuild

env:
  global:
    # speeds up installation of html-proofer
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
