title: Jamie Davies
description: >
  A recent computer science graduate from the University of Southampton, now
  working for Netcraft

# URL format
baseurl: ""
url: ""
permalink: "/:year/:title/"

# Build settings
markdown: kramdown
theme: bland
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: :compressed
