title: Jamie Davies
author: Jamie Davies
email: jamie@jamiedavies.me
description: > # this means to ignore newlines until "baseurl:"
  A recent computer science graduate from the University of Southampton, now
  working for Netcraft

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: bland
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
