title: Jamie Davies
description: >
  A recent computer science graduate from the University of Southampton, now
  working for Netcraft

# URL format
baseurl: ""
url: ""
permalink: "/:year/:title/"

# Where post media is stored (images, downloads, etc)
media_path: "/media"

# Build settings
markdown: kramdown
theme: bland
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: :compressed

# Default layouts
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post
